AWSTemplateFormatVersion: '2010-09-09'
Description: 'IMDSpoof Honeypot Deployment for Security Workshop - Deploys EC2 instance with spoofed IMDS service'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'AWS Credentials Configuration'
        Parameters:
          - AWSAccessKeyId
          - AWSSecretAccessKey
          - AWSSessionToken
      - Label:
          default: 'Network Configuration (Optional)'
        Parameters:
          - VpcId
          - SubnetId
    ParameterLabels:
      AWSAccessKeyId:
        default: 'AWS Access Key ID'
      AWSSecretAccessKey:
        default: 'AWS Secret Access Key'
      AWSSessionToken:
        default: 'AWS Session Token (Optional)'

Parameters:
  AWSAccessKeyId:
    Type: String
    Description: 'AWS Access Key ID for IMDS spoofing (e.g., AKIA...)'
    MinLength: "16"
    MaxLength: "128"
    AllowedPattern: '^[A-Z0-9]+$'
    ConstraintDescription: 'Must be a valid AWS Access Key ID format'
    NoEcho: true

  AWSSecretAccessKey:
    Type: String
    Description: 'AWS Secret Access Key for IMDS spoofing'
    MinLength: "16"
    MaxLength: "2048"
    NoEcho: true

  AWSSessionToken:
    Type: String
    Description: 'Optional: AWS Session Token (leave default if not provided)'
    Default: 'IQoJb3Jpz2cXpQRkpVX3Uf////////////xMdLZHNjbmtGZ2NhL//////////wPbEVN6UGVwIgJ7I5bAOpTzLKpWxIb7sZR74Dq9MNYW/3kThIUWKqDNCoZP+iSbXHHTZuSILnIlFfnT+QcPnlS/tOzaGPxwhuFFnhpMKVtQqgfhWtdMFUPbUPxbtIIhVqPpueagIfbsAjbRRCvrLkRylooW+JDmiqymJQzeReoiWqCnSgzyvYnsSVZRHeNANqYFq/aMqTJ/KvXlbtbzjTPNHahpZXGamgvAtniqkJqhBYGPGQaGKi+cPqqEZdYIYPzMaYjtJgNtGmBoDxkKQeKRVlEtpkAdWMjXXWYm+BnddxxrNAnBcNwrjBtSp/OpQdjvhFfahhKxyEDinpjDkkRrfWTdkmwaMmOjDBHbtUotMJPekH+KtArZuX+HsSAoNfZlwHhnvFTC+jFqgwXelfAfOhrDxlEvadqCAGLOVKLBBtQjFwrXkDmHccVVdUZZEkzQqLuYRlMWVgUpJZQroHHK/uEBiYRYKrpdkEhcWwYPRkPagFLYzdWRTnhxtHGoNNTyq/EHBOKog+rtYUH+QJ+MBYf/ALKSUzIzij/WNH/bNfkVpqPdYPMYtmfk/CBpXoDgj+VweJZJGzHdXP/zBlvqvmHaswckLfSVWtoNLspdlNJUua+JMy/QxlEeghQiNPMmixPv+Ofn/IpLsHmhFYRceGt+EcVKKayGicwSiUXPFG/JafLNLNwQjMVbMb+WGm/CMsYfnNengS/XYYh/hRXNnSQzzcmscXjouqKhzmWhc/HGc+/wNRmrtFVwhTldmFAxiqmScziGDFvxlXeoEThIqKoVBqeqLiWNBeDzjKlwfVbiyFtQfrXWFwzVvTtJ+rDjLPk+SVgapQVRwpGlAUtjEkbuLyCYqLeO/uqGhKJhMZKjNTQ/aVPXkWR/CGxTmLWuEMZQFuSWlIFqYvyyfPHWQPCWDPwnjkGkkjNrJUhfkOXNpHAnBNHYpXUMidzsggFUccMzJIuqVLGAKgUENdRxsqqJiR+FbOgpnjaKEzyqWcLjiGDxMVpIdNqyWuJniNCRqyFKLkDsCi+MejhGVMVSr'
    MaxLength: "2048"
    NoEcho: true

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: 'VPC ID for the honeypot instance (uses default VPC if available)'

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: 'Subnet ID for the honeypot instance (use a public subnet for Session Manager access)'

Resources:
  # IAM Role for EC2 Instance with SSM Session Manager access
  IMDSpoofInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'IMDSpoof-InstanceRole-${AWS::StackName}'
      Description: 'IAM Role for IMDSpoof honeypot instance with SSM Session Manager access'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'
      Tags:
        - Key: Name
          Value: !Sub 'IMDSpoof-Role-${AWS::StackName}'
        - Key: Purpose
          Value: 'SecurityWorkshop-Honeypot'

  # Instance Profile for EC2
  IMDSpoofInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub 'IMDSpoof-InstanceProfile-${AWS::StackName}'
      Roles:
        - !Ref IMDSpoofInstanceRole

  # Security Group - No SSH, only outbound for SSM and package downloads
  IMDSpoofSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub 'IMDSpoof-SG-${AWS::StackName}'
      GroupDescription: 'Security Group for IMDSpoof honeypot - No inbound SSH, Session Manager access only'
      VpcId: !Ref VpcId
      SecurityGroupIngress: []  # No inbound rules - Session Manager uses outbound HTTPS
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: 'HTTPS for SSM Session Manager and package downloads'
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: 'HTTP for package manager (yum/dnf)'
      Tags:
        - Key: Name
          Value: !Sub 'IMDSpoof-SG-${AWS::StackName}'
        - Key: Purpose
          Value: 'SecurityWorkshop-Honeypot'

  # EC2 Instance with IMDSpoof
  IMDSpoofInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      IamInstanceProfile: !Ref IMDSpoofInstanceProfile
      SecurityGroupIds:
        - !Ref IMDSpoofSecurityGroup
      SubnetId: !Ref SubnetId
      # Use latest Amazon Linux 2023 AMI
      ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}'
      Tags:
        - Key: Name
          Value: !Sub 'IMDSpoof-Honeypot-${AWS::StackName}'
        - Key: Purpose
          Value: 'SecurityWorkshop-Honeypot'
        - Key: DeceptionTool
          Value: 'IMDSpoof'
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e

          # Log all output to a file for debugging
          exec > >(tee /var/log/imdspoof-setup.log)
          exec 2>&1

          echo "=== IMDSpoof Honeypot Installation Started ==="
          echo "Timestamp: $(date)"

          # Get Instance ID from real IMDS before it gets spoofed
          INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
          echo "Instance ID: $INSTANCE_ID"

          # Update system
          echo "[1/8] Updating system packages..."
          dnf update -y

          # Install required packages
          echo "[2/8] Installing dependencies (git, golang, iptables)..."
          dnf install -y git golang iptables-services

          # Clone IMDSpoof repository
          echo "[3/8] Cloning IMDSpoof repository..."
          cd /opt
          if [ -d "IMDSpoof" ]; then
            rm -rf IMDSpoof
          fi
          git clone https://github.com/c0ffee0wl/IMDSpoof.git
          cd IMDSpoof

          # Replace credentials in IMDS.go using sed
          echo "[4/8] Injecting AWS credentials into IMDS.go..."

          # Escape special characters in credentials for sed
          ACCESS_KEY="${AWSAccessKeyId}"
          SECRET_KEY="${AWSSecretAccessKey}"
          SESSION_TOKEN="${AWSSessionToken}"

          # Replace accessKey (line 20)
          sed -i 's|var accessKey string = "HoneyToken"|var accessKey string = "'"$ACCESS_KEY"'"|g' IMDS.go

          # Replace secretAccessKey (line 21)
          sed -i 's|var secretAccessKey string = "HoneyToken"|var secretAccessKey string = "'"$SECRET_KEY"'"|g' IMDS.go

          # Replace token (line 22) - only if it starts with the default value
          sed -i 's|var token string = "IQoJb3Jpz2cXpQRkpVX3Uf[^"]*"|var token string = "'"$SESSION_TOKEN"'"|g' IMDS.go

          echo "Credentials injected successfully"

          # Initialize Go module and install dependencies
          echo "[5/8] Installing Go dependencies..."
          go mod init imdspoof 2>/dev/null || true
          go mod tidy
          go get github.com/fatih/color

          # Compile the binary
          echo "[6/8] Compiling IMDSpoof binary..."
          go build -o /bin/IMDS IMDS.go
          chmod +x /bin/IMDS

          # Create systemd service
          echo "[7/8] Creating systemd service..."
          cat > /etc/systemd/system/IMDS.service << 'EOF'
          [Unit]
          Description=IMDSpoof - AWS IMDS Honeypot Service
          After=multi-user.target network-online.target
          Wants=network-online.target

          [Service]
          Type=simple
          ExecStart=/bin/IMDS
          User=root
          Restart=always
          RestartSec=10
          StandardOutput=journal
          StandardError=journal

          [Install]
          WantedBy=multi-user.target
          EOF

          # Enable and start the service
          echo "[8/8] Enabling and starting IMDSpoof service..."
          systemctl daemon-reload
          systemctl enable IMDS.service
          systemctl start IMDS.service

          # Verify service status
          sleep 2
          if systemctl is-active --quiet IMDS.service; then
            echo "✓ IMDSpoof service is running successfully"
            systemctl status IMDS.service --no-pager
          else
            echo "✗ IMDSpoof service failed to start"
            systemctl status IMDS.service --no-pager
            exit 1
          fi

          # Test the spoofed IMDS endpoint
          echo "Testing spoofed IMDS endpoint..."
          sleep 1
          curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/ec2-admin || echo "Endpoint test failed (this is expected if iptables needs more time)"

          echo "=== IMDSpoof Honeypot Installation Completed ==="
          echo "Instance is ready for workshop use"
          echo "Access via: aws ssm start-session --target $INSTANCE_ID"

Outputs:
  InstanceId:
    Description: 'EC2 Instance ID of the IMDSpoof honeypot'
    Value: !Ref IMDSpoofInstance
    Export:
      Name: !Sub '${AWS::StackName}-InstanceId'

  SessionManagerCommand:
    Description: 'AWS CLI command to connect via Session Manager'
    Value: !Sub 'aws ssm start-session --target ${IMDSpoofInstance} --region ${AWS::Region}'

  TestIMDSCommand:
    Description: 'Command to test the spoofed IMDS service (run inside the instance)'
    Value: 'curl http://169.254.169.254/latest/meta-data/iam/security-credentials/ec2-admin'

  ServiceStatusCommand:
    Description: 'Command to check IMDSpoof service status (run inside the instance)'
    Value: 'sudo systemctl status IMDS.service'

  Region:
    Description: 'AWS Region where the honeypot is deployed'
    Value: !Ref AWS::Region

  SecurityNote:
    Description: 'Important security information'
    Value: 'This honeypot spoofs the AWS IMDS service. Do NOT deploy on instances that use real IMDS credentials!'

  MonitoringReminder:
    Description: 'Monitoring reminder'
    Value: 'Monitor your email for alerts when attackers attempt to use the injected credentials'
